import { firebaseApp, auth, db, storage, firebaseReady } from './firebase-config.js';
const $ = (s,p=document)=>p.querySelector(s); const $$=(s,p=document)=>[...p.querySelectorAll(s)];
const state={user:null,lang:localStorage.getItem('lang')||'en',theme:localStorage.getItem('theme')||'light',rate:{last:0,count:0}};
const API_BASE = localStorage.getItem('apiBase') || (location.port === '5500' ? 'http://127.0.0.1:8000/api' : `${location.origin}/api`);
const i18n={en:{hero_title:'Share moments that matter.',hero_sub:'Create posts, connect with friends, and discover trending content worldwide.',get_started:'Get Started',login:'Login',signup:'Sign Up'},es:{hero_title:'Comparte momentos que importan.',hero_sub:'Crea publicaciones, conecta con amigos y descubre tendencias globales.',get_started:'Comenzar',login:'Iniciar sesión',signup:'Registrarse'}};
const routes={'/':renderLanding,'/login':renderLogin,'/signup':renderSignup,'/feed':renderFeed,'/explore':renderExplore,'/profile':renderProfile,'/notifications':renderNotifications,'/messages':renderMessages,'/admin':renderAdmin};
function toast(msg,ok=true){const d=document.createElement('div');d.className='card';d.style.position='fixed';d.style.right='12px';d.style.bottom='12px';d.style.zIndex=99;d.style.borderColor=ok?'#86efac':'#fecaca';d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),2200)}
function t(k){return i18n[state.lang]?.[k]||k}
function applyI18n(){ $$('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n)); $('#langBtn').textContent=state.lang.toUpperCase(); }
function navigate(path){history.pushState({},'',path);router()}
window.addEventListener('popstate',router); document.addEventListener('click',e=>{const b=e.target.closest('[data-link]');if(b){e.preventDefault();navigate(b.dataset.link)}});
function applyTheme(){document.documentElement.style.filter=state.theme==='dark'?'invert(1) hue-rotate(180deg)':'none';$('#themeBtn').textContent=state.theme==='dark'?'☀':'☾'}
$('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';localStorage.setItem('theme',state.theme);applyTheme()};
$('#langBtn').onclick=()=>{state.lang=state.lang==='en'?'es':'en';localStorage.setItem('lang',state.lang);applyI18n();router()};
$('#logoutBtn').onclick=async()=>{try{if(firebaseReady&&auth) await auth.signOut(); localStorage.removeItem('mockUser'); state.user=null; updateAuthUI(); navigate('/')}catch{toast('Logout failed',false)}};
function updateAuthUI(){const authed=!!state.user; $$('.authed').forEach(e=>e.classList.toggle('hidden',!authed)); $$('.admin-only').forEach(e=>e.classList.toggle('hidden',!(authed&&state.user?.role==='admin')))}
function setView(tid){const tpl=$(tid); $('#view').innerHTML=''; $('#view').appendChild(tpl.content.cloneNode(true)); applyI18n()}
async function api(path,opt={}){try{const headers={ 'Content-Type':'application/json', ...(opt.headers||{}) }; const r=await fetch(path.startsWith('http')?path:`${API_BASE}${path}`,{...opt,headers}); if(!r.ok){let msg='API '+r.status; try{const err=await r.json(); msg=err.detail||msg;}catch{} throw new Error(msg)} if(r.status===204) return null; return await r.json()}catch(e){throw new Error(e.message||'Network error')}}
function antiSpam(){const n=Date.now(); if(n-state.rate.last<5000) state.rate.count++; else state.rate.count=1; state.rate.last=n; if(state.rate.count>3) throw new Error('Slow down: spam protection active')}
async function router(){const path=location.pathname; const fn=routes[path]||renderLanding; try{await fn()}catch(e){$('#view').innerHTML='<section class="card">Error loading page</section>'; toast(e.message,false)} updateAuthUI(); applyI18n();}
function currentUser(){if(state.user) return state.user; const m=localStorage.getItem('mockUser'); return m?JSON.parse(m):null}
async function renderLanding(){setView('#landing-template')}
async function renderLogin(){setView('#login-template'); $('#loginForm').onsubmit=async(e)=>{e.preventDefault(); const fd=new FormData(e.target); try{antiSpam(); const email=String(fd.get('email')||'').trim(); const password=String(fd.get('password')||''); if(firebaseReady&&auth){await auth.signInWithEmailAndPassword(email,password); state.user={email,name:email.split('@')[0],verified:true,role:'user'};} else {const res=await api('/auth/login',{method:'POST',body:JSON.stringify({email,password})}); state.user=res.user;} localStorage.setItem('mockUser',JSON.stringify(state.user)); toast('Logged in'); navigate('/feed')}catch(err){toast(err.message,false)}}}
async function renderSignup(){setView('#signup-template'); $('#signupForm').onsubmit=async(e)=>{e.preventDefault(); const fd=new FormData(e.target); try{antiSpam(); const name=String(fd.get('name')||'').trim(); const email=String(fd.get('email')||'').trim(); const password=String(fd.get('password')||''); if(firebaseReady&&auth){const cred=await auth.createUserWithEmailAndPassword(email,password); await cred.user.sendEmailVerification(); state.user={name,email,verified:false,role:'user'};} else {const res=await api('/auth/signup',{method:'POST',body:JSON.stringify({name,email,password})}); state.user=res.user;} localStorage.setItem('mockUser',JSON.stringify(state.user)); toast('Registered. Verify email to unlock all features.'); navigate('/feed')}catch(err){toast(err.message,false)}}}
async function renderFeed(){if(!currentUser()) return navigate('/login'); setView('#feed-template'); const stories=['You','Ana','Leo','Mia','Noah']; $('#storiesBar').innerHTML=stories.map(s=>`<div class='story'><div class='tile'>${s[0]}</div><small>${s}</small></div>`).join(''); $('#postForm').onsubmit=async(e)=>{e.preventDefault(); try{antiSpam(); const fd=new FormData(e.target); const content=String(fd.get('content')||'').trim(); if(!content) throw new Error('Write something first'); await api('/posts',{method:'POST',body:JSON.stringify({author_email:currentUser().email,content,media:String(fd.get('media')||'')})}); e.target.reset(); await drawPosts(); toast('Posted')}catch(err){toast(err.message,false)}}; await drawPosts();}
async function drawPosts(){const box=$('#postList'); let posts=[]; try{const res=await api('/posts'); posts=res.posts||[]}catch(err){toast(err.message,false)} if(!posts.length) posts=[{id:'demo',author:'SocialSphere',content:'Welcome to your personalized feed!',media:'',likes:4,saved:false,comments:['Nice!'],created:Date.now()}]; box.innerHTML=posts.map(p=>`<article class='card post'><div class='meta'>@${p.author} · ${new Date(p.created).toLocaleString()}</div><p>${p.content}</p>${p.media?`<a href='${p.media}' target='_blank'>Open media</a>`:''}<div class='actions'><button class='btn like' data-id='${p.id}'>♥ ${p.likes}</button><button class='btn comment' data-id='${p.id}'>💬 ${p.comments.length}</button><button class='btn save' data-id='${p.id}' data-saved='${p.saved?1:0}'>${p.saved?'Saved':'Save'}</button><button class='btn del' data-id='${p.id}'>Delete</button></div></article>`).join(''); box.onclick=async(e)=>{const b=e.target.closest('button'); if(!b) return; const id=b.dataset.id; try{if(b.classList.contains('like')) await api(`/posts/${id}/like`,{method:'POST'}); if(b.classList.contains('save')){const isSaved=b.dataset.saved==='1'; await api(`/posts/${id}/${isSaved?'unsave':'save'}`,{method:'POST'});} if(b.classList.contains('comment')){const c=prompt('Comment'); if(c) await api(`/posts/${id}/comment`,{method:'POST',body:JSON.stringify({author:currentUser().name,comment:c})})} if(b.classList.contains('del')) await api(`/posts/${id}`,{method:'DELETE'}); await drawPosts();}catch(err){toast(err.message,false)}};}
async function renderExplore(){if(!currentUser()) return navigate('/login'); setView('#explore-template'); const grid=$('#exploreGrid'); const load=async(q='trending')=>{try{const data=await api('https://dummyjson.com/posts/search?q='+encodeURIComponent(q)); grid.innerHTML=(data.posts||[]).slice(0,12).map(p=>`<div class='tile'>#${(p.tags?.[0]||'trend')}</div>`).join('')}catch{grid.innerHTML='<div class="card">Could not load explore data.</div>'}}; $('#searchBtn').onclick=()=>load($('#searchInput').value||'news'); load();}
async function renderProfile(){if(!currentUser()) return navigate('/login'); setView('#profile-template'); const u=currentUser(); $('#profileBox').innerHTML=`<p><b>${u.name}</b></p><p>${u.email}</p><p>Status: ${u.verified?'Verified':'Unverified'}</p><div class='row'><button class='btn' id='followBtn'>Follow</button><button class='btn'>Unfollow</button></div>`;}
async function renderNotifications(){if(!currentUser()) return navigate('/login'); setView('#notifications-template'); try{const res=await api(`/notifications/${encodeURIComponent(currentUser().email)}`); $('#notificationsList').innerHTML=(res.notifications||[]).map(x=>`<div class='card'>${x.title}</div>`).join('')}catch(err){$('#notificationsList').innerHTML='<div class="card">Could not load notifications.</div>'; toast(err.message,false)}}
async function renderMessages(){if(!currentUser()) return navigate('/login'); setView('#messages-template'); try{const res=await api(`/messages/${encodeURIComponent(currentUser().email)}`); $('#dmList').innerHTML=(res.messages||[]).map(x=>`<div class='card'>${x.from_user}: ${x.text}</div>`).join('')}catch(err){$('#dmList').innerHTML='<div class="card">Could not load messages.</div>'; toast(err.message,false)}}
async function renderAdmin(){if(!currentUser()||currentUser().role!=='admin') return navigate('/feed'); setView('#admin-template'); $('#flaggedBtn').onclick=async()=>{try{const data=await api('/admin/flagged'); $('#moderationList').innerHTML=(data||[]).map(x=>`<div class='card row between'><span>${x}</span><span><button class='btn'>Approve</button> <button class='btn'>Remove</button></span></div>`).join('')}catch(err){toast(err.message,false)}};}
(function init(){state.user=currentUser(); $('#year').textContent=new Date().getFullYear(); applyTheme(); updateAuthUI(); router();})();